// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4PRZM9yTE6vVBtCOgkeM0RKRBCRZOKI',
    appId: '1:757057358375:web:956a9a5deadce8086b5c02',
    messagingSenderId: '757057358375',
    projectId: 'ayaintel-assignment',
    authDomain: 'ayaintel-assignment.firebaseapp.com',
    storageBucket: 'ayaintel-assignment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJf43bJ7isfup18ZOdG6kiktf2xSaIJxQ',
    appId: '1:757057358375:android:37d98e53aea3f5e76b5c02',
    messagingSenderId: '757057358375',
    projectId: 'ayaintel-assignment',
    storageBucket: 'ayaintel-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChTFIQ6vnpX9wfQ9QJcua9pcnS_WL_Nkw',
    appId: '1:757057358375:ios:8192cf62ee4bb8d96b5c02',
    messagingSenderId: '757057358375',
    projectId: 'ayaintel-assignment',
    storageBucket: 'ayaintel-assignment.appspot.com',
    iosBundleId: 'com.example.ayaintelAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChTFIQ6vnpX9wfQ9QJcua9pcnS_WL_Nkw',
    appId: '1:757057358375:ios:8192cf62ee4bb8d96b5c02',
    messagingSenderId: '757057358375',
    projectId: 'ayaintel-assignment',
    storageBucket: 'ayaintel-assignment.appspot.com',
    iosBundleId: 'com.example.ayaintelAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD4PRZM9yTE6vVBtCOgkeM0RKRBCRZOKI',
    appId: '1:757057358375:web:cb1224fb0a92f5266b5c02',
    messagingSenderId: '757057358375',
    projectId: 'ayaintel-assignment',
    authDomain: 'ayaintel-assignment.firebaseapp.com',
    storageBucket: 'ayaintel-assignment.appspot.com',
  );

}