//* Generated school and subjects list from ChatGPT

final kSchoolNames = [
  'Maplewood Academy',
  'Crestview High School',
  'Greenfield Institute',
  'Summit Hill School',
  'Riverside Learning Center',
  'Beacon Grove Academy',
  'Harmony Valley High',
  'Silver Oak Academy',
  'Northstar Educational Institute',
  'Willow Creek School',
  'Horizon Springs Academy',
  'Pine Ridge High School',
  'Oakwood Scholars',
  'Brookside Academy',
  'Evergreen Learning Center',
  'Crestwood Academy',
  'Lakeview High School',
  'Maple Valley Institute',
  'Starbright Academy',
  'Clearview School',
  'Valley Forge Academy',
  'Redwood High School',
  'Lighthouse Learning Academy',
  'Sunflower Academy',
  'Oak Hill Institute',
  'Blue Ridge School',
  'Riverstone Academy',
  'Ashwood High School',
  'Harmony Hills Academy',
  'Crestview Scholars',
  'Westwood Academy',
  'Pinnacle High School',
  'Golden Valley Institute',
  'Silver Birch Academy',
  'Meadowlark School',
  'Cedar Crest Academy',
  'Willowbend High School',
  'Summit Ridge Institute',
  'Maple Leaf Academy',
  'Horizon View School',
  'Riverbend Academy',
  'Springdale High School',
  'Ash Grove Academy',
  'Lighthouse High School',
  'Forest Hill School',
  'Eagle’s Nest Academy',
  'Starlight Learning Center',
  'West Valley Institute',
  'Summit Academy',
  'Oak Park High School',
  'Clearwater Academy',
  'Trailblazer High School',
  'Maple Heights School',
  'Heritage Academy',
  'Crestwood Learning Center',
  'Birchwood High School',
  'Silver Valley Institute',
  'Harmony Grove Academy',
  'River Valley High',
  'Pine Valley Academy',
  'Lakeside Institute',
  'Horizon Academy',
  'Cedar Valley School',
  'Oak Ridge High School',
  'Bluebell Academy',
  'Meadowview Institute',
  'Sunrise Academy',
  'Westlake High School',
  'Birch Hill Academy',
  'Valleyview School',
  'Crestwood Institute',
  'Maple Ridge Academy',
  'Riverside Scholars',
  'Golden Oaks High School',
  'Harmony Springs Academy',
  'Pine Hollow School',
  'Evergreen Academy',
  'Sun Valley Institute',
  'Meadowbrook High School',
  'Crestwood Academy',
  'Lakeshore Learning Center',
  'Silver Lake Academy',
  'Harmony Heights School',
  'Ridgewood Academy',
  'Willow Springs High School',
  'Bright Futures Academy',
  'Horizon Heights School',
  'Riverstone Scholars',
  'Cedar Lake Institute',
  'Maplewood Scholars',
  'Pinecrest Academy',
  'Lakeside Scholars',
  'Summit Springs School',
  'Green Hills Academy',
  'Starview High School',
  'Meadowlark Academy',
  'Crystal Lake Institute',
  'Harmony Valley School',
  'Silver Pines Academy',
  'Trail Ridge High School'
];
final kSchoolSubjects = [
  'Mathematics',
  'Science',
  'English Language Arts',
  'History',
  'Geography',
  'Physical Education',
  'Art',
  'Music',
  'Computer Science',
  'Biology',
  'Chemistry',
  'Physics',
  'Literature',
  'Social Studies',
  'Health Education',
  'Foreign Language',
  'Drama',
  'Economics',
  'Statistics',
  'Environmental Science',
  'Philosophy',
  'Psychology',
  'Sociology',
  'Business Studies',
  'Information Technology',
  'Engineering',
  'Creative Writing',
  'Debate',
  'Graphic Design',
  'Astronomy',
  'Media Studies',
  'Robotics',
  'Dance',
  'Woodshop',
  'Culinary Arts',
  'Speech',
  'Ethics',
  'Law Studies',
  'Current Events',
  'Native Language Studies',
  'Digital Media',
  'Marketing',
  'Fashion Design',
  'Creative Arts',
  'Life Skills',
  'Computer Programming',
  'Statistics',
  'App Development',
  'Web Design',
  'Photography',
  'Journalism',
  'Game Design',
  'Cybersecurity',
  'Marine Biology',
  'Theater Arts',
  'Leadership',
  'Civics',
  'Forensic Science',
  'Personal Finance',
  'Construction Technology',
  'Automotive Technology',
  'Agriculture Science',
  'Astronomy',
  'Horticulture',
  'Special Education',
  'Advanced Placement (AP) Courses',
  'International Baccalaureate (IB) Courses',
  'Project-Based Learning',
  'Entrepreneurship',
  'Global Studies',
  'Cultural Studies',
  'Media Literacy',
  'Public Speaking',
  'Environmental Studies'
];
